que5.3
ashok-choudhary-0/firebase-project-1 pull request #1
Opened 2023-09-30 10:23 UTC by ashok-choudhary-0

2023-09-30 10:31 UTC, amrit56789 commented on config/firebaseConfig.js
> +const { initializeApp } = require("firebase/app");
new text document.txt ?

2023-09-30 10:31 UTC, amrit56789 commented on config/firebaseConfig.js
> +const firebaseConfig = {
instead of this you can use serviceAccount.json file.

2023-09-30 10:31 UTC, amrit56789 commented on controllers/authController.js
> +const { createUserWithEmailAndPassword } = require("firebase/auth")
not auth controller you are creating  user.

2023-09-30 10:31 UTC, amrit56789 commented on index.js
> +const authRoutes = require("./routes/authRoutes")
not auth its users.

2023-09-30 10:31 UTC, amrit56789 commented on index.js
> +app.use("/auth", authRoutes)
/user

2023-09-30 10:31 UTC, amrit56789 commented on controllers/authController.js
> +const signup = async (req, res) => {
createUser

2023-09-30 10:31 UTC, amrit56789 commented on controllers/authController.js
> +    const data = await createUserWithEmailAndPassword(auth, email, password);
newUser.

2023-10-03 13:06 UTC, meanstack9716 requested changes

2023-10-03 13:06 UTC, meanstack9716 commented on .gitignore
> +package-lock.json
Package lock should not be here

2023-10-03 13:06 UTC, meanstack9716 commented on config/firebaseConfig.js
> +
Why too many white slaces?

2023-10-05 05:00 UTC, yuvrajInno requested changes

2023-10-05 05:00 UTC, yuvrajInno commented on controllers/userController.js
> +  const {email, password} = req.body;
code not formatted @ashok-choudhary-0

2023-10-05 05:00 UTC, yuvrajInno commented on controllers/userController.js
> +const signup = async (req, res) => {
function name should be camleCase @ashok-choudhary-0

2023-10-05 07:35 UTC, merged